### ISSUE TITLE
ServiceNow Resource Types

### ISSUE THREAD

**Issue by AdamCoulterOz** [coveo/terraform-provider-servicenow#17]
Would it make sense to add resource types to manage Configuration Items, Service Request Definitions, KB Articles, etc? We are looking for a way to configure these with Terraform also. Would you be happy to take PRs?

**Comment by mikegron** [comment]
I would gladly accept PRs if you feel like it! Although I'm not quite sure how it would work in your case, for instance you have raw text files that you want to use to create and sync KB Articles?
